export const FootballDetail = {
    "resp": {
        "againstRecord": [
            {
                "matchTime": "2015-11-04 03:45", 
                "leagueName": "欧冠杯", 
                "leagueId": "91", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "加拉塔", 
                "awayTeamId": 507, 
                "hostTeamId": 458, 
                "hostScore": "2", 
                "awayScore": "1", 
                "result": "负", 
                "asiaTapeResult": "-1走", 
                "scoreTapeResult": "2.75大"
            }, 
            {
                "matchTime": "2015-10-22 02:45", 
                "leagueName": "欧冠杯", 
                "leagueId": "91", 
                "hostTeamName": "加拉塔", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 507, 
                "hostScore": "2", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "0.25赢", 
                "scoreTapeResult": "2.5大"
            }, 
            {
                "matchTime": "2011-11-13 03:30", 
                "leagueName": "友谊赛", 
                "leagueId": "47", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "加拉塔", 
                "awayTeamId": 507, 
                "hostTeamId": 458, 
                "hostScore": "2", 
                "awayScore": "0", 
                "result": "负", 
                "asiaTapeResult": "-0.5输", 
                "scoreTapeResult": "2.5小"
            }, 
            {
                "matchTime": "2008-11-07 03:30", 
                "leagueName": "欧罗巴杯", 
                "leagueId": "95", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "加拉塔", 
                "awayTeamId": 507, 
                "hostTeamId": 458, 
                "hostScore": "0", 
                "awayScore": "2", 
                "result": "胜", 
                "asiaTapeResult": "-0.75赢", 
                "scoreTapeResult": "2.5小"
            }
        ], 
        "newAgainstRecordDesc": "加拉塔,4,2,0,2,5,5,2,2,2,1,1", 
        "newQwarLeagueResultDesc": "本菲卡,10,8,0,2,30,11,6,4,7,1,2", 
        "hostLeagueResultDesc": "加拉塔萨近10场战绩:7胜3平0负,进26失9", 
        "newHostLeagueResultDesc": "加拉塔萨,10,7,3,0,26,9,5,5,8,1,1", 
        "qwarLeagueResultDesc": "本菲卡近10场战绩:8胜0平2负,进30失11", 
        "awayRecord": [
            {
                "matchTime": "2019-02-11 01:30", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "葡国民", 
                "awayTeamId": 2, 
                "hostTeamId": 458, 
                "hostScore": "10", 
                "awayScore": "0", 
                "result": "胜", 
                "asiaTapeResult": "-2.25赢", 
                "scoreTapeResult": "3.5大"
            }, 
            {
                "matchTime": "2019-02-07 04:45", 
                "leagueName": "葡杯", 
                "leagueId": "66", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "里斯本竞", 
                "awayTeamId": 461, 
                "hostTeamId": 458, 
                "hostScore": "2", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "-0.5赢", 
                "scoreTapeResult": "2.5大"
            }, 
            {
                "matchTime": "2019-02-04 01:30", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "里斯本竞", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 461, 
                "hostScore": "2", 
                "awayScore": "4", 
                "result": "胜", 
                "asiaTapeResult": "0赢", 
                "scoreTapeResult": "2.5大"
            }, 
            {
                "matchTime": "2019-01-30 03:00", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "博维斯塔", 
                "awayTeamId": 452, 
                "hostTeamId": 458, 
                "hostScore": "5", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "-2赢", 
                "scoreTapeResult": "3大"
            }, 
            {
                "matchTime": "2019-01-23 03:45", 
                "leagueName": "葡联杯", 
                "leagueId": "441", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "波尔图", 
                "awayTeamId": 463, 
                "hostTeamId": 458, 
                "hostScore": "1", 
                "awayScore": "3", 
                "result": "负", 
                "asiaTapeResult": "0.25输", 
                "scoreTapeResult": "2.25大"
            }, 
            {
                "matchTime": "2019-01-19 05:15", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "吉马良斯", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 841, 
                "hostScore": "0", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "0.75赢", 
                "scoreTapeResult": "2.5小"
            }, 
            {
                "matchTime": "2019-01-16 04:45", 
                "leagueName": "葡杯", 
                "leagueId": "66", 
                "hostTeamName": "吉马良斯", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 841, 
                "hostScore": "0", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "0.75赢", 
                "scoreTapeResult": "2.5小"
            }, 
            {
                "matchTime": "2019-01-12 03:00", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "圣克拉拉", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 869, 
                "hostScore": "0", 
                "awayScore": "2", 
                "result": "胜", 
                "asiaTapeResult": "1.25赢", 
                "scoreTapeResult": "2.75小"
            }, 
            {
                "matchTime": "2019-01-07 01:30", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "本菲卡", 
                "awayTeamName": "里奥阿维", 
                "awayTeamId": 468, 
                "hostTeamId": 458, 
                "hostScore": "4", 
                "awayScore": "2", 
                "result": "胜", 
                "asiaTapeResult": "-2走", 
                "scoreTapeResult": "3.25大"
            }, 
            {
                "matchTime": "2019-01-03 04:15", 
                "leagueName": "葡超", 
                "leagueId": "32", 
                "hostTeamName": "波尔蒂斯", 
                "awayTeamName": "本菲卡", 
                "awayTeamId": 458, 
                "hostTeamId": 1342, 
                "hostScore": "2", 
                "awayScore": "0", 
                "result": "负", 
                "asiaTapeResult": "1输", 
                "scoreTapeResult": "2.75小"
            }
        ], 
        "hostRecord": [
            {
                "matchTime": "2019-02-10 23:59", 
                "leagueName": "土超", 
                "leagueId": "37", 
                "hostTeamName": "加拉塔萨", 
                "awayTeamName": "特拉布宗", 
                "awayTeamId": 521, 
                "hostTeamId": 507, 
                "hostScore": "3", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "-0.75赢", 
                "scoreTapeResult": "2.75大"
            }, 
            {
                "matchTime": "2019-02-07 01:30", 
                "leagueName": "土杯", 
                "leagueId": "144", 
                "hostTeamName": "加拉塔萨", 
                "awayTeamName": "哈塔斯堡", 
                "awayTeamId": 5166, 
                "hostTeamId": 507, 
                "hostScore": "2", 
                "awayScore": "0", 
                "result": "胜", 
                "asiaTapeResult": "-1.25赢", 
                "scoreTapeResult": "2.75小"
            }, 
            {
                "matchTime": "2019-02-02 23:59", 
                "leagueName": "土超", 
                "leagueId": "37", 
                "hostTeamName": "阿兰亚", 
                "awayTeamName": "加拉塔萨", 
                "awayTeamId": 507, 
                "hostTeamId": 3902, 
                "hostScore": "1", 
                "awayScore": "1", 
                "result": "平", 
                "asiaTapeResult": "0.25输", 
                "scoreTapeResult": "2.5小"
            }, 
            {
                "matchTime": "2019-01-30 00:45", 
                "leagueName": "土杯", 
                "leagueId": "144", 
                "hostTeamName": "加拉塔萨", 
                "awayTeamName": "波卢斯", 
                "awayTeamId": 5438, 
                "hostTeamId": 507, 
                "hostScore": "4", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "-1赢", 
                "scoreTapeResult": "2.5大"
            }, 
            {
                "matchTime": "2019-01-26 23:59", 
                "leagueName": "土超", 
                "leagueId": "37", 
                "hostTeamName": "高士特比", 
                "awayTeamName": "加拉塔萨", 
                "awayTeamId": 507, 
                "hostTeamId": 1434, 
                "hostScore": "0", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "0.5赢", 
                "scoreTapeResult": "2.75小"
            }, 
            {
                "matchTime": "2019-01-23 00:45", 
                "leagueName": "土杯", 
                "leagueId": "144", 
                "hostTeamName": "波卢斯", 
                "awayTeamName": "加拉塔萨", 
                "awayTeamId": 507, 
                "hostTeamId": 5438, 
                "hostScore": "0", 
                "awayScore": "1", 
                "result": "胜", 
                "asiaTapeResult": "0.75赢", 
                "scoreTapeResult": "2.75小"
            }, 
            {
                "matchTime": "2019-01-19 23:59", 
                "leagueName": "土超", 
                "leagueId": "37", 
                "hostTeamName": "加拉塔萨", 
                "awayTeamName": "安卡拉古", 
                "awayTeamId": 511, 
                "hostTeamId": 507, 
                "hostScore": "6", 
                "awayScore": "0", 
                "result": "胜", 
                "asiaTapeResult": "-1.75赢", 
                "scoreTapeResult": "3.25大"
            }, 
            {
                "matchTime": "2019-01-12 22:00", 
                "leagueName": "球会友谊", 
                "leagueId": "47", 
                "hostTeamName": "莱比红牛", 
                "awayTeamName": "加拉塔萨", 
                "awayTeamId": 507, 
                "hostTeamId": 11930, 
                "hostScore": "1", 
                "awayScore": "1", 
                "result": "平", 
                "asiaTapeResult": "-0.5赢", 
                "scoreTapeResult": "3小"
            }, 
            {
                "matchTime": "2019-01-08 20:00", 
                "leagueName": "球会友谊", 
                "leagueId": "47", 
                "hostTeamName": "埃斯基", 
                "awayTeamName": "加拉塔萨", 
                "awayTeamId": 507, 
                "hostTeamId": 3825, 
                "hostScore": "3", 
                "awayScore": "3", 
                "result": "平", 
                "asiaTapeResult": "0走", 
                "scoreTapeResult": "2.5大"
            }, 
            {
                "matchTime": "2018-12-23 23:59", 
                "leagueName": "土超", 
                "leagueId": "37", 
                "hostTeamName": "加拉塔萨", 
                "awayTeamName": "锡瓦体育", 
                "awayTeamId": 1352, 
                "hostTeamId": 507, 
                "hostScore": "4", 
                "awayScore": "2", 
                "result": "胜", 
                "asiaTapeResult": "-0.75赢", 
                "scoreTapeResult": "2.75大"
            }
        ]
    }, 
    "ro": {
        "respCode": "0000", 
        "respMesg": "处理成功"
    }
}
